// Question model - represents a multiple choice quiz question
// Generated by AI from lecture content for Challenge Mode

class Question {
  final String question; // The question text to display
  final List<String> options; // 4 answer options (A, B, C, D)
  final int correctAnswer; // Index of correct option (0-3)
  final String explanation; // Why the answer is correct (shown after answering)

  // Constructor - all fields required for a valid question
  Question({
    required this.question,
    required this.options,
    required this.correctAnswer,
    required this.explanation,
  });

  // Factory constructor - creates Question from JSON (API response)
  // Handles null values with defaults to prevent crashes
  factory Question.fromJson(Map<String, dynamic> json) {
    return Question(
      question: json['question'] as String? ?? '', // Default empty string
      options:
          (json['options'] as List<dynamic>?) // Cast to List
              ?.map((e) => e.toString()) // Convert each to String
              .toList() ??
          [], // Default to empty list if null
      correctAnswer:
          json['correctAnswer'] as int? ?? 0, // Default to first option
      explanation: json['explanation'] as String? ?? '',
    );
  }

  // Convert Question to JSON for API requests or storage
  Map<String, dynamic> toJson() {
    return {
      'question': question,
      'options': options,
      'correctAnswer': correctAnswer,
      'explanation': explanation,
    };
  }

  // Convert Question to Map for Firestore storage
  // Same as toJson but named for Firestore convention
  Map<String, dynamic> toMap() {
    return {
      'question': question,
      'options': options,
      'correctAnswer': correctAnswer,
      'explanation': explanation,
    };
  }

  // Factory constructor - creates Question from Firestore document
  // Similar to fromJson but named for Firestore convention
  factory Question.fromMap(Map<String, dynamic> map) {
    return Question(
      question: map['question'] as String? ?? '',
      options:
          (map['options'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          [],
      correctAnswer: map['correctAnswer'] as int? ?? 0,
      explanation: map['explanation'] as String? ?? '',
    );
  }

  // Validate question has all required data
  // Returns true only if question is properly formed
  bool isValid() {
    return question.isNotEmpty && // Has question text
        options.length == 4 && // Exactly 4 options
        correctAnswer >= 0 && // Valid index
        correctAnswer < 4; // Within bounds
  }
}
